/*
 * Ratatoskr Android app
 * Copyright (C) 2026  Ratatoskr contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
package io.github.xexanos.ratatoskr.ui

import android.graphics.Matrix
import android.graphics.PathMeasure
import androidx.compose.animation.core.LinearEasing
import androidx.compose.animation.core.RepeatMode
import androidx.compose.animation.core.animateFloat
import androidx.compose.animation.core.infiniteRepeatable
import androidx.compose.animation.core.rememberInfiniteTransition
import androidx.compose.animation.core.tween
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.asAndroidPath
import androidx.compose.ui.graphics.asComposePath
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import io.github.xexanos.ratatoskr.R
import io.github.xexanos.ratatoskr.ui.theme.LocalReducedMotion
import io.github.xexanos.ratatoskr.ui.theme.RatatoskrTheme
import kotlinx.coroutines.delay

// Path data lifted verbatim from docs/logo/ratatoskr-spinner.svg: FRAME_D is the filled knot
// outline (line 7), ROUTE_D is the <path id="ratatoskr-route"> centre line the runner traces
// (line 8). They are NOT regenerated by tools/logo automatically - if the logo changes, copy the
// new "d" strings here. The SVG viewBox is "-8 -8 272 272" (see VIEW_BOX below).
private const val FRAME_D =
    "M152.51,17.74 L146.47,11.10 L140.65,5.67 L134.64,1.08 L128.00,-2.99 L119.59,2.32 L111.79,8.87 " +
        "L104.18,16.94 L95.45,27.86 L106.19,30.29 L112.40,22.71 L117.67,17.10 L122.55,12.69 L128.00,8.67 " +
        "L135.23,14.20 L142.63,21.62 L149.58,30.00 L165.65,50.98 L175.66,61.98 L181.33,66.99 L187.36,71.45 " +
        "L194.56,75.97 L202.83,80.53 L203.41,69.50 L191.01,61.79 L185.77,57.68 L180.90,53.10 L172.45,43.49 " +
        "L152.51,17.74 Z M75.90,27.78 L67.01,26.58 L59.06,26.16 L51.50,26.50 L43.80,27.66 L40.77,37.13 " +
        "L39.01,47.16 L38.36,58.23 L38.70,72.21 L48.49,67.17 L48.38,57.37 L48.80,49.68 L49.70,43.17 " +
        "L51.29,36.58 L60.39,36.18 L70.83,37.10 L81.54,39.06 L107.33,44.80 L122.07,46.79 L129.64,46.98 " +
        "L137.12,46.52 L145.55,45.36 L154.81,43.54 L148.16,34.71 L133.71,36.78 L127.05,36.99 L120.37,36.62 " +
        "L107.73,34.69 L75.90,27.78 Z M23.67,84.72 L16.09,89.51 L9.73,94.30 L4.16,99.42 L-1.00,105.25 " +
        "L2.77,114.46 L7.87,123.28 L14.49,132.17 L23.73,142.66 L27.99,132.51 L21.61,125.08 L16.99,118.91 " +
        "L13.49,113.35 L10.48,107.28 L17.19,101.12 L25.78,95.12 L35.24,89.73 L58.69,77.55 L71.26,69.60 " +
        "L77.18,64.89 L82.61,59.72 L88.32,53.42 L94.25,46.07 L83.48,43.57 L73.74,54.45 L68.78,58.89 " +
        "L63.42,62.90 L52.49,69.55 L23.67,84.72 Z M20.26,161.91 L17.53,170.45 L15.73,178.21 L14.76,185.71 " +
        "L14.56,193.49 L23.37,198.12 L32.94,201.60 L43.73,204.16 L57.55,206.25 L54.29,195.74 L44.62,194.15 " +
        "L37.12,192.40 L30.86,190.38 L24.65,187.67 L25.83,178.64 L28.56,168.52 L32.34,158.31 L42.47,133.91 " +
        "L47.00,119.74 L48.50,112.32 L49.34,104.87 L49.66,96.37 L49.48,86.93 L39.63,91.94 L39.16,106.54 " +
        "L38.21,113.13 L36.68,119.64 L32.58,131.76 L20.26,161.91 Z M67.16,222.97 L70.66,231.53 L74.27,238.63 " +
        "L78.35,245.00 L83.20,251.09 L92.92,248.97 L102.49,245.49 L112.40,240.51 L124.34,233.23 L115.07,227.27 " +
        "L106.65,232.27 L99.77,235.75 L93.68,238.22 L87.19,240.14 L82.29,232.46 L77.87,222.96 L74.20,212.71 " +
        "L66.28,187.50 L60.63,173.74 L57.02,167.09 L52.87,160.84 L47.66,154.12 L41.45,147.01 L37.13,157.18 " +
        "L46.15,168.67 L49.66,174.32 L52.67,180.30 L57.33,192.21 L67.16,222.97 Z M142.44,239.86 L150.62,244.17 " +
        "L157.95,247.28 L165.17,249.54 L172.80,251.09 L178.89,243.22 L183.98,234.40 L188.37,224.22 L192.83,210.96 " +
        "L181.91,212.36 L178.67,221.60 L175.64,228.68 L172.56,234.49 L168.81,240.14 L160.13,237.41 L150.64,232.97 " +
        "L141.24,227.47 L118.96,213.25 L105.79,206.34 L98.75,203.57 L91.56,201.45 L83.25,199.66 L73.92,198.20 " +
        "L77.15,208.77 L91.44,211.77 L97.76,213.84 L103.91,216.48 L115.14,222.62 L142.44,239.86 Z M210.96,204.40 " +
        "L220.00,202.45 L227.62,200.12 L234.60,197.21 L241.44,193.49 L241.04,183.55 L239.27,173.53 L236.10,162.90 " +
        "L230.99,149.88 L223.52,157.97 L226.98,167.14 L229.21,174.51 L230.59,180.93 L231.35,187.67 L222.94,191.16 " +
        "L212.81,193.86 L202.08,195.69 L175.88,199.12 L161.35,202.28 L154.17,204.69 L147.30,207.69 L139.78,211.66 " +
        "L131.70,216.54 L140.96,222.56 L153.83,215.67 L160.02,213.19 L166.42,211.26 L178.96,208.75 L210.96,204.40 " +
        "Z M240.67,133.20 L246.33,125.89 L250.67,119.22 L254.15,112.50 L257.00,105.25 L250.31,97.89 L242.50,91.35 " +
        "L233.24,85.25 L220.96,78.56 L220.44,89.56 L228.98,94.36 L235.42,98.57 L240.61,102.61 L245.52,107.28 " +
        "L241.32,115.36 L235.30,123.93 L228.26,132.23 L210.39,151.70 L201.29,163.47 L197.34,169.92 L194.00,176.64 " +
        "L190.80,184.52 L187.74,193.45 L198.71,192.11 L204.14,178.55 L207.29,172.68 L210.95,167.09 L218.95,157.10 " +
        "L240.67,133.20 Z M217.65,59.56 L217.29,50.33 L216.32,42.42 L214.67,35.04 L212.20,27.66 L202.34,26.32 " +
        "L192.16,26.32 L181.14,27.61 L167.43,30.37 L174.10,39.13 L183.73,37.32 L191.38,36.40 L197.94,36.16 " +
        "L204.71,36.59 L206.68,45.47 L207.59,55.91 L207.52,66.80 L206.35,93.20 L206.95,108.06 L208.07,115.54 " +
        "L209.83,122.84 L212.43,130.93 L215.83,139.73 L223.37,131.66 L218.82,117.78 L217.46,111.26 L216.67,104.62 " +
        "L216.37,91.83 L217.65,59.56 Z"
private const val ROUTE_D =
    "M236.43,190.60 C213.03,204.13 182.81,199.57 157.41,208.81 C132.02,218.06 111.80,240.97 85.18,245.65 " +
        "C67.79,224.95 67.04,194.41 53.52,171.00 C40.01,147.59 13.93,131.66 4.70,106.26 C22.06,85.54 52.02,79.49 " +
        "72.72,62.12 C93.43,44.75 104.59,16.30 128.00,2.80 C151.41,16.30 162.57,44.75 183.28,62.12 C203.98,79.49 " +
        "233.94,85.54 251.30,106.26 C242.07,131.66 215.99,147.59 202.48,171.00 C188.96,194.41 188.21,224.95 " +
        "170.82,245.65 C144.20,240.97 123.98,218.06 98.59,208.81 C73.19,199.57 42.97,204.13 19.57,190.60 " +
        "C19.56,163.57 38.61,139.68 43.31,113.07 C48.00,86.45 38.26,57.48 47.52,32.09 C74.14,27.38 100.97,42.00 " +
        "128.00,42.00 C155.03,42.00 181.86,27.38 208.48,32.09 C217.74,57.48 208.00,86.45 212.69,113.07 " +
        "C217.39,139.68 236.44,163.57 236.43,190.60 Z"

// viewBox "-8 -8 272 272": origin offset 8, side 272. Point (x,y) -> ((x+8)*s, (y+8)*s).
private const val VIEW_BOX_SIDE = 272f
private const val VIEW_BOX_OFFSET = 8f

// Comet geometry, in viewBox units, matching the SVG reference (stroke-width 7, runner radii).
private const val STROKE_WIDTH = 7f
private const val RUNNER_RADIUS = 6.5f
private const val HALO_RADIUS = 12f
private const val TAIL_FRACTION = 0.20f // length of the fading comet tail, as a fraction of the path
private const val TAIL_SEGMENTS = 24
private const val TAIL_MAX_ALPHA = 0.30f // matches the SVG stroke opacity
private const val HALO_ALPHA = 0.22f
private const val CYCLE_MILLIS = 2400 // one lap of the runner, matching the SVG animation

/**
 * The Ratatoskr brand loader: the woven-knot mark with a copper squirrel running the strand.
 *
 * Renders the static knot [frameColor] and, unless motion is reduced, a copper "runner" head with
 * a fading comet tail that traces the strand centre line once every [CYCLE_MILLIS] ms - the Android
 * equivalent of the SMIL-animated reference SVG, redrawn in a [Canvas] with a [PathMeasure]. Centres
 * itself, so it drops into `Box(Modifier.fillMaxSize(), contentAlignment = Center) { ... }` like
 * [EmptyState]. Prefer showing it only after a short delay (see [rememberDelayedVisible]) so quick
 * waits don't flash it.
 */
@Composable
fun KnotLoader(
    modifier: Modifier = Modifier,
    size: Dp = 96.dp,
    label: String? = null,
    frameColor: Color = MaterialTheme.colorScheme.secondary,
    runnerColor: Color = MaterialTheme.colorScheme.primary,
) {
    val reduced = LocalReducedMotion.current
    // Under reduced motion the knot holds still, so a visible text label must carry the wait
    // (design rule 3) - the motion can no longer signal it. Fall back to a generic one when the
    // caller gives none.
    val effectiveLabel = label ?: if (reduced) stringResource(R.string.app_loading) else null
    val sidePx = with(LocalDensity.current) { size.toPx() }
    val geometry = remember(sidePx) { KnotGeometry(sidePx) }
    Column(
        modifier = modifier,
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center,
    ) {
        // The knot announces itself to TalkBack only when no visible label does; otherwise it is
        // decorative and the label carries the meaning - one announcement, not two.
        val knotDescription =
            if (effectiveLabel == null) stringResource(R.string.knot_loader_description) else null
        val knotModifier = Modifier
            .size(size)
            .then(
                if (knotDescription != null) {
                    Modifier.semantics { contentDescription = knotDescription }
                } else {
                    Modifier
                },
            )
        if (reduced) {
            StaticKnot(knotModifier, geometry, frameColor)
        } else {
            AnimatedKnot(knotModifier, geometry, frameColor, runnerColor)
        }
        if (effectiveLabel != null) {
            Spacer(Modifier.height(16.dp))
            Text(
                effectiveLabel,
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                textAlign = TextAlign.Center,
            )
        }
    }
}

/** Parsed, pixel-scaled paths plus a reusable [PathMeasure] for one [sidePx] size. */
private class KnotGeometry(sidePx: Float) {
    val frame: Path = PathParser().parsePathString(FRAME_D).toPath()
        .apply { fillType = PathFillType.EvenOdd }
    val route: Path = PathParser().parsePathString(ROUTE_D).toPath()
    val measure: PathMeasure
    val length: Float
    val strokePx: Float = STROKE_WIDTH * sidePx / VIEW_BOX_SIDE
    val runnerPx: Float = RUNNER_RADIUS * sidePx / VIEW_BOX_SIDE
    val haloPx: Float = HALO_RADIUS * sidePx / VIEW_BOX_SIDE

    init {
        val scale = sidePx / VIEW_BOX_SIDE
        // (x,y) -> ((x + 8) * scale): preTranslate applies to the point first, then scale.
        val matrix = Matrix().apply {
            setScale(scale, scale)
            preTranslate(VIEW_BOX_OFFSET, VIEW_BOX_OFFSET)
        }
        frame.asAndroidPath().transform(matrix)
        route.asAndroidPath().transform(matrix)
        measure = PathMeasure(route.asAndroidPath(), false)
        length = measure.length
    }
}

@Composable
private fun AnimatedKnot(modifier: Modifier, geometry: KnotGeometry, frameColor: Color, runnerColor: Color) {
    // No animation-inspector labels: they are tooling-only and the UX guardrail (check-ux.sh
    // rule 4) can't tell an animation label from user-facing copy, so it flags `label = "..."`.
    val transition = rememberInfiniteTransition()
    val head by transition.animateFloat(
        initialValue = 0f,
        targetValue = 1f,
        animationSpec = infiniteRepeatable(
            animation = tween(CYCLE_MILLIS, easing = LinearEasing),
            repeatMode = RepeatMode.Restart,
        ),
    )
    Canvas(modifier) {
        drawPath(geometry.frame, color = frameColor)
        // Read the animated head only inside the draw lambda: this invalidates the draw phase
        // each frame without triggering recomposition.
        drawComet(geometry, head, runnerColor)
    }
}

@Composable
private fun StaticKnot(modifier: Modifier, geometry: KnotGeometry, frameColor: Color) {
    Canvas(modifier) {
        drawPath(geometry.frame, color = frameColor)
    }
}

/**
 * Draws the comet: a fading tail of [TAIL_SEGMENTS] sub-segments trailing the runner head, then the
 * runner itself (a translucent halo under a solid dot). [head] is the head position as a fraction
 * `[0,1)` of the path length.
 */
private fun DrawScope.drawComet(geo: KnotGeometry, head: Float, color: Color) {
    val length = geo.length
    if (length <= 0f) return
    val headDist = head * length
    val tailLen = length * TAIL_FRACTION
    val seg = tailLen / TAIL_SEGMENTS
    val scratch = android.graphics.Path()
    for (i in 0 until TAIL_SEGMENTS) {
        val stop = headDist - i * seg
        val start = headDist - (i + 1) * seg
        // Nearest the head is brightest; fade to transparent at the tail end.
        val alpha = TAIL_MAX_ALPHA * (1f - i.toFloat() / TAIL_SEGMENTS)
        for ((s, e) in wrappedRanges(start, stop, length)) {
            scratch.rewind()
            geo.measure.getSegment(s, e, scratch, true)
            drawPath(
                scratch.asComposePath(),
                color = color.copy(alpha = alpha),
                style = Stroke(width = geo.strokePx, cap = StrokeCap.Round, join = StrokeJoin.Round),
            )
        }
    }
    val pos = FloatArray(2)
    geo.measure.getPosTan(headDist.mod(length), pos, null)
    val center = Offset(pos[0], pos[1])
    drawCircle(color.copy(alpha = HALO_ALPHA), radius = geo.haloPx, center = center)
    drawCircle(color, radius = geo.runnerPx, center = center)
}

/**
 * Maps the distance range `[start, stop]` onto `[0, length]`, splitting it into two ranges when it
 * crosses the closed-path seam at `length`. [PathMeasure.getSegment] neither wraps nor clamps, so
 * feeding it a range that straddles the seam would silently draw nothing. Pure, so the wrap/split
 * arithmetic is unit-testable without a device.
 */
internal fun wrappedRanges(start: Float, stop: Float, length: Float): List<Pair<Float, Float>> {
    if (length <= 0f) return emptyList()
    val s = start.mod(length)
    val e = stop.mod(length)
    return when {
        s == e && stop - start >= length -> listOf(0f to length) // full lap
        s <= e -> listOf(s to e)
        else -> listOf(s to length, 0f to e) // straddles the seam
    }
}

// --- Previews (render in Android Studio without a running server) --------------------------

@Preview(name = "Knot loader", widthDp = 360, heightDp = 300)
@Composable
internal fun KnotLoaderPreview() = RatatoskrTheme {
    Surface {
        Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
            KnotLoader(label = stringResource(R.string.app_loading))
        }
    }
}

@Preview(name = "Knot loader - reduced motion", widthDp = 360, heightDp = 300)
@Composable
internal fun KnotLoaderReducedPreview() = RatatoskrTheme {
    androidx.compose.runtime.CompositionLocalProvider(LocalReducedMotion provides true) {
        Surface {
            Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                KnotLoader(label = stringResource(R.string.app_loading))
            }
        }
    }
}

/**
 * Shows nothing until [active] has been true for [delayMillis], then stays visible until it goes
 * false again. Gates the (expensive) knot loader behind a short threshold so quick waits never
 * flash it; only genuinely slow waits escalate to the animation.
 */
@Composable
fun rememberDelayedVisible(active: Boolean, delayMillis: Long = 500L): Boolean {
    var visible by remember { mutableStateOf(false) }
    LaunchedEffect(active) {
        if (active) {
            delay(delayMillis)
            visible = true
        } else {
            visible = false
        }
    }
    return visible
}
