import org.openapitools.generator.gradle.plugin.tasks.GenerateTask

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.openapi.generator)
    // Runs moshi-kotlin-codegen over the generated client sources so every model gets a
    // compile-time JsonAdapter - no reflective KotlinJsonAdapterFactory, no kotlin-reflect
    // in the APK, and R8 can shrink the release build (SPEC section 8).
    alias(libs.plugins.ksp)
}

android {
    namespace = "io.github.xexanos.ratatoskr.network"
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        minSdk = 26
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    // One copy of the test fakes and wire-format fixtures, consumed by BOTH the JVM unit
    // tests and the instrumented integration tests (they are separate source sets and cannot
    // see each other). Without this the fakes existed twice and had to be hand-synced.
    testFixtures {
        enable = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

// Generate the Kotlin client from the version-pinned contract submodule (SPEC section 4).
// The output is never committed (see .gitignore); the domain/UI layer never touches these
// types directly - the wrapper in this module maps them to domain models (SPEC section 13).
// AGP owns the output directory: addGeneratedSourceDirectory (below) wires it and the task
// ordering, so we do not set outputDir here. sourceFolder="" makes the generator write the
// package tree straight into that directory instead of a nested src/main/kotlin.
val openApiGenerate = tasks.named<GenerateTask>("openApiGenerate") {
    generatorName.set("kotlin")
    library.set("jvm-retrofit2")
    inputSpec.set(
        rootProject.layout.projectDirectory
            .file("contract/ratatoskr-server/contract/openapi.yaml")
            .asFile.absolutePath
    )
    packageName.set("io.github.xexanos.ratatoskr.network.generated")
    apiPackage.set("io.github.xexanos.ratatoskr.network.generated.api")
    modelPackage.set("io.github.xexanos.ratatoskr.network.generated.model")
    configOptions.set(
        mapOf(
            "dateLibrary" to "java8",
            "serializationLibrary" to "moshi",
            // Emit @JsonClass(generateAdapter = true) models and drop the reflective
            // KotlinJsonAdapterFactory from the generated Serializer; the adapters are
            // generated by KSP (moshi-kotlin-codegen). Enums keep Moshi's built-in handling,
            // so the PlaybackState unknown-value fallback in RatatoskrClientFactory is
            // unaffected (SPEC sections 4 and 8).
            "moshiCodeGen" to "true",
            "useCoroutines" to "true",
            "sourceFolder" to "",
        )
    )
    // Only the client sources; no test/doc scaffolding.
    generateApiTests.set(false)
    generateModelTests.set(false)
    generateApiDocumentation.set(false)
    generateModelDocumentation.set(false)
}

androidComponents {
    onVariants { variant ->
        // Registered as *kotlin* sources (the generator emits only .kt) so that both the
        // built-in Kotlin compilation and the KSP task (moshi-kotlin-codegen, above) see
        // them; a java-source registration is not guaranteed to feed KSP.
        variant.sources.kotlin?.addGeneratedSourceDirectory(openApiGenerate) { it.outputDir }
    }
}

dependencies {
    // Runtime dependencies the generated jvm-retrofit2/moshi client expects.
    api(libs.retrofit)
    api(libs.retrofit.converter.moshi)
    api(libs.retrofit.converter.scalars)
    api(libs.okhttp)
    implementation(libs.okhttp.logging.interceptor)
    api(libs.moshi)
    api(libs.moshi.adapters)
    ksp(libs.moshi.kotlin.codegen)
    api(libs.kotlinx.coroutines.core)
    implementation(libs.androidx.datastore.preferences)

    // Shared test fixtures (FakeTokenAccess, WireFixtures, HttpsMockServer) consumed by this
    // module's unit + instrumented tests AND the :app UI integration tests. HttpsMockServer's
    // PUBLIC surface exposes JUnit's ExternalResource (superclass) and MockWebServer/MockResponse
    // (return types), so those are `api`. okhttp-tls (HeldCertificate/HandshakeCertificates) is
    // used only in private members, so it stays `implementation` - consumers don't need it.
    testFixturesApi(libs.junit)
    testFixturesApi(libs.okhttp.mockwebserver)
    testFixturesImplementation(libs.okhttp.tls)

    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.coroutines.core)
    testImplementation(libs.okhttp.mockwebserver)
    // testFixturesImplementation's okhttp-tls does not propagate here; the TLS pin unit tests
    // mint their own certificates with HeldCertificate.Builder and need it directly.
    testImplementation(libs.okhttp.tls)
    testImplementation(testFixtures(project(":core-network")))

    // Instrumented integration tests (SPEC section 9): drive the real client assembly through
    // RatatoskrClientFactory against MockWebServer over HTTPS, on the real Android runtime.
    androidTestImplementation(libs.androidx.junit)
    // androidx.test.ext:junit does not pull the instrumentation runner in transitively; without
    // this the test APK lacks AndroidJUnitRunner and the process crashes before any test runs.
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.kotlinx.coroutines.core)
    androidTestImplementation(libs.okhttp.mockwebserver)
    androidTestImplementation(libs.okhttp.tls)
    androidTestImplementation(libs.androidx.datastore.preferences)
    androidTestImplementation(testFixtures(project(":core-network")))
}
